version: "3.5"
volumes:
  grafana_data:
  mongo_data:
  postgres_data:

services:
  db:
    image: mongo:4.0
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_data:/data/db
    ports:
      - 27022:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  sql:
    image: postgres:13.3-buster
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: GRES_password

  redis:
    image: redis:6.0-alpine
    ports:
      - 6391:6379

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    user: "1000"
    depends_on:
      - sql
    ports:
      - "8088:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin!!
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=webdav
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=ilgizar-candlestick-panel

  src:
    depends_on:
      - redis
      - db
      - sql
    container_name: steve-the-trade-bot
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/SteveTheTradeBot"
      - "./.aws:/root/.aws"
      #find src* | grep  '/bin$' | sed 's/^/ - SteveTheTradeBot\//'
      - /SteveTheTradeBot/src/SteveTheTradeBot.Api/bin
      - /SteveTheTradeBot/src/SteveTheTradeBot.Api.Lambda/bin
      - /SteveTheTradeBot/src/SteveTheTradeBot.Core/bin
      - /SteveTheTradeBot/src/SteveTheTradeBot.Dal/bin
      - /SteveTheTradeBot/src/SteveTheTradeBot.Dal.MongoDb/bin
      - /SteveTheTradeBot/src/SteveTheTradeBot.Sdk/bin
      - /SteveTheTradeBot/src/SteveTheTradeBot.Shared/bin
      - /SteveTheTradeBot/src/SteveTheTradeBot.Utilities/bin
      - /SteveTheTradeBot/test/SteveTheTradeBot.Api.Tests/bin
      - /SteveTheTradeBot/test/SteveTheTradeBot.Core.Tests/bin
      #find src* | grep  '/obj$' | sed 's/^/ - /SteveTheTradeBot\//'
      - /SteveTheTradeBot/src/SteveTheTradeBot.Api/obj
      - /SteveTheTradeBot/src/SteveTheTradeBot.Api.Lambda/obj
      - /SteveTheTradeBot/src/SteveTheTradeBot.Core/obj
      - /SteveTheTradeBot/src/SteveTheTradeBot.Dal/obj
      - /SteveTheTradeBot/src/SteveTheTradeBot.Dal.MongoDb/obj
      - /SteveTheTradeBot/src/SteveTheTradeBot.Sdk/obj
      - /SteveTheTradeBot/src/SteveTheTradeBot.Shared/obj
      - /SteveTheTradeBot/src/SteveTheTradeBot.Utilities/obj
      - /SteveTheTradeBot/test/SteveTheTradeBot.Api.Tests/obj
      - /SteveTheTradeBot/test/SteveTheTradeBot.Core.Tests/obj

    environment:
      - DOTNET_ENVIRONMENT=Development
      - MongoConnection=mongodb://db:27017/steve-the-trade-bot
      - MongoDatabase=steve-the-trade-bot
      - NpgsqlConnection=Host=sql;Database=SteveTheTradeBotSample;Username=postgres;Password=GRES_password;Port=5432
      - RedisHost=redis
      - App__HostUrl=http://localhost:5000
      - OpenId__Origins=http://localhost:5000,http://localhost:84,http://localhost:3000
    ports:
      - 5001:5000
    entrypoint: top -b
    logging:
      driver: none
