// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML;
using SteveTheTradeBotML.Model;

namespace SteveTheTradeBot.ML.Model
{
    public class ConsumeModel
    {
        private readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> _predictionEngine;
        private readonly string _modelPath;

        public ConsumeModel(string modelZip = @"MLModel.zip")
        {
            _modelPath = modelZip;
            _predictionEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(CreatePredictionEngine);
        }

        // For more info on consuming ML.NET models, visit https://aka.ms/mlnet-consume
        // Method for consuming model in your app
        public ModelOutput Predict(ModelInput input)
        {
            return _predictionEngine.Value.Predict(input);
        }

        public PredictionEngine<ModelInput, ModelOutput> CreatePredictionEngine()
        {
            // Create new MLContext
            var mlContext = new MLContext();

            // Load model & create prediction engine
            var modelPath = _modelPath;
            var mlModel = mlContext.Model.Load(modelPath, out _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
