// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SteveTheTradeBotML.Model
{
    public class ModelInput
    {
        [ColumnName("Date"), LoadColumn(0)]
        public string Date { get; set; }


        [ColumnName("Close"), LoadColumn(1)]
        public float Close { get; set; }


        [ColumnName("Volume"), LoadColumn(2)]
        public float Volume { get; set; }


        [ColumnName("macd"), LoadColumn(3)]
        public float Macd { get; set; }


        [ColumnName("rsi14"), LoadColumn(4)]
        public float Rsi14 { get; set; }


        [ColumnName("ema100"), LoadColumn(5)]
        public float Ema100 { get; set; }


        [ColumnName("ema200"), LoadColumn(6)]
        public float Ema200 { get; set; }


        [ColumnName("roc100"), LoadColumn(7)]
        public float Roc100 { get; set; }


        [ColumnName("roc200"), LoadColumn(8)]
        public float Roc200 { get; set; }


        [ColumnName("roc100sma"), LoadColumn(9)]
        public float Roc100sma { get; set; }


        [ColumnName("roc200sma"), LoadColumn(10)]
        public float Roc200sma { get; set; }


        [ColumnName("supertrend"), LoadColumn(11)]
        public float Supertrend { get; set; }


        [ColumnName("macdsignal"), LoadColumn(12)]
        public float Macdsignal { get; set; }


        [ColumnName("macdhistogram"), LoadColumn(13)]
        public float Macdhistogram { get; set; }


        [ColumnName("supertrendlower"), LoadColumn(14)]
        public float Supertrendlower { get; set; }


        [ColumnName("supertrendupper"), LoadColumn(15)]
        public float Supertrendupper { get; set; }


        [ColumnName("FutureDate"), LoadColumn(16)]
        public string FutureDate { get; set; }


        [ColumnName("FutureClose"), LoadColumn(17)]
        public float FutureClose { get; set; }


        [ColumnName("FutureChange"), LoadColumn(18)]
        public float FutureChange { get; set; }


    }
}
